package browser;

import chrriis.dj.nativeswing.NSOption;
import chrriis.dj.nativeswing.swtimpl.NativeInterface;
import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;
import java.awt.BorderLayout;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/*
 * Notes:
 * 1) The DJProject [http://djproject.sourceforge.net/ns/index.html]
 * 2) Dowloaded and placed in graham/DJProject
 * 3) The eclipse-swt toolkit shipped with DJProject is 32bit
 * 4) Getting the swt for Win64:
 * Required downloading the latest eclipse swt toolkit for windows 64bit.
 * Downloaded from archive:
 * http://download.eclipse.org/eclipse/downloads/drops4/S-4.3M5a-201302041400/
 * noting that DJProject requires a version of swt > 3.75.
 * 5) The layout on the web browser panel must be set to BorderLayout, otherwise the content will not show.
 * 6) Forum comment on using Mozilla with DJProject: http://sourceforge.net/p/djproject/discussion/671154/thread/efe9ce26/
 * XULRunner: https://developer.mozilla.org/en/docs/XULRunner
 * 7) Downloaded windows version: https://developer.mozilla.org/en-US/docs/XULRunner_1.9.2_Release_Notes and added to graham\xulrunner
 * 8) Extracted fies and added to \program files (x86)\xulrunner\1.9.2
 * 9) Ran the command "xulrunner.exe --register-global" in the xulrunner folder
 */

/**
 * Javadoc added by Graham
 * Another Javadoc added by Graham
 * @author Graham Seed
 */
public class WebBrowser extends javax.swing.JFrame {

  protected JWebBrowser mWebBrowser;
  
  /**
   * Creates new form WebBrowser
   */
  public WebBrowser() {
    initComponents();
    initialise();
  }

  private void initialise() {
    
    NSOption nsOption = JWebBrowser.useXULRunnerRuntime();
    //NSOption nsOptionWebKit = JWebBrowser.useWebkitRuntime();
    
    mWebBrowser = new JWebBrowser();
    //mWebBrowser = new JWebBrowser(nsOption);
    //mWebBrowser = new JWebBrowser(nsOptionWebKit);
    
    boolean jsEnabled = mWebBrowser.isJavascriptEnabled();
    mWebBrowser.setJavascriptEnabled(true);
    jsEnabled = mWebBrowser.isJavascriptEnabled();
    
    String browserType = mWebBrowser.getBrowserType();
    String browserVer = mWebBrowser.getBrowserVersion();
    
    // disable menu/buttons
    mWebBrowser.setMenuBarVisible(false);
    mWebBrowser.setButtonBarVisible(false);
    mWebBrowser.setStatusBarVisible(false);
    mWebBrowser.setLocationBarVisible(false);
    
    //webBrowser.navigate("http://www.google.com");
    //mWebBrowser.navigate("http://www.schematicltd.com");
    mWebBrowser.navigate("http://www.browserproperties.com"); // details of web browser
    
    //String pdfLoc = "file:///c:/graham/mantis/mantisbt-1.2.14/doc/en/developers.pdf";
    //mWebBrowser.navigate(pdfLoc);
    
    mjContentPanel.add(mWebBrowser, BorderLayout.CENTER);
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    mjContentPanel = new javax.swing.JPanel();
    mjButtonPanel = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    mjLanuchBrowserButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    mjContentPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    mjContentPanel.setLayout(new java.awt.BorderLayout());

    jButton1.setText("OK");
    mjButtonPanel.add(jButton1);

    jButton2.setText("Close");
    mjButtonPanel.add(jButton2);

    mjLanuchBrowserButton.setText("LaunchBrowser");
    mjLanuchBrowserButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        mjLanuchBrowserButtonActionPerformed(evt);
      }
    });
    mjButtonPanel.add(mjLanuchBrowserButton);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(mjContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(mjButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(mjContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(mjButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // handles the "LaunchBrowser" button
  private void mjLanuchBrowserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mjLanuchBrowserButtonActionPerformed
    try {
      String url = "http://www.schematicltd.com";
      java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
    } catch (IOException ex) {
      System.out.println("exception: " + ex.getMessage());
    }
  }//GEN-LAST:event_mjLanuchBrowserButtonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(WebBrowser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(WebBrowser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(WebBrowser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(WebBrowser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    NativeInterface.open();

    /* Create and display the form */
//    java.awt.EventQueue.invokeLater(new Runnable() {
//      public void run() {
//        new WebBrowser().setVisible(true);
//      }
//    });

    SwingUtilities.invokeLater(new Runnable() {
      public void run() {
        new WebBrowser().setVisible(true);
      }
    });

    NativeInterface.runEventPump();
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JPanel mjButtonPanel;
  private javax.swing.JPanel mjContentPanel;
  private javax.swing.JButton mjLanuchBrowserButton;
  // End of variables declaration//GEN-END:variables
}
